### ISSUE TITLE
Failure to link to boost on Ubuntu

### ISSUE THREAD

**Issue by molpopgen** [putnampp/clotho#1]
With boost 1.55 on Ubuntu, clotho fails to link to the program_options library.  I can confirm that the library is installed properly (in /usr/lib) as I use it for other projects with no issues.

Abbreviated output:

Linking CXX executable ../../bin/benchmark_all_neutral
../../lib/libCLOTHO_commandline.so: undefined reference to `typeinfo for boost::program_options::error_with_option_name'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::error_with_option_name::what() const'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_options::options_description const&)'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::to_internal(std::string const&)'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::detail::cmdline::run()'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::arg'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::variables_map::variables_map()'
../../lib/libCLOTHO_commandline.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'

**Comment by putnampp** [comment]
Interesting. Fedora does not require linking  commandline library against program_options, but Ubuntu does.

Should be corrected in the last push.

**Comment by molpopgen** [comment]
That fixed it--thanks!
